kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-cvmfsplugin-provisioner
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cvmfs-csi.name" . }}
    helm.sh/chart: {{ include "cvmfs-csi.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-cvmfsplugin-provisioner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cvmfs-csi.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: csi-cvmfsplugin-provisioner
    spec:
      serviceAccount: cvmfs-provisioner
      containers:
        - name: csi-provisioner
          image: {{ .Values.csiProvisioner.image }}
          args:
            {{- range $arg := .Values.csiProvisioner.args }}
            - {{ $arg | quote -}}
            {{- end }}
          env:
            - name: ADDRESS
              value: unix:/csi/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          hostPath:
            path: {{ .Values.csiPlugin.pluginDirectory }}
            type: DirectoryOrCreate
